name: TestEnv

on:
  workflow_dispatch:

jobs:
  testenv:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04]
    runs-on: ${{matrix.os}}
    timeout-minutes: 2
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: "Swift Version"
      run: swift --version